# Generated by Django 4.0.4 on 2022-05-24 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_order_address_alter_order_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderUpdate',
            fields=[
                ('update_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(default='')),
                ('update_dec', models.CharField(max_length=50000)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
